resolver: lts-7.3
compiler: ghcjs-0.2.1.9007003_ghc-8.0.1

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007003_ghc-8.0.1:
          url: http://ghcjs.tolysz.org/ghc-8.0-2016-10-11-lts-7.3-9007003.tar.gz
          sha1: 3196fd5eaed670416083cf3678396d02c50096de

packages:
- '.'
- location:
    git: git@github.com:reflex-frp/reflex.git
    commit: 91299fce0bb2caddfba35af6608df57dd31e3690
- location:
    git: git@github.com:reflex-frp/reflex-dom.git
    commit: 66b6d35773fcb337ab38ebce02c4b23baeae721e

extra-deps:
- ghcjs-dom-0.2.4.0
- ref-tf-0.4.0.1
- data-default-0.6.0
- data-default-instances-base-0.1.0.1
- prim-uniq-0.1.0.1
- zenc-0.1.1
